---
apiVersion: api.cerbos.dev/v1
resourcePolicy:
    version: "default"
    resource: "member:server-settings"
    rules:
        - actions: ["*"]
          effect: EFFECT_ALLOW
          roles:
              - "admin"
